---
title: "Maine Prisoner Advocacy Coalition Project 2"
subtitle: "Visualizing Prison and Parole Data"
date: "Wednesday, May 25 2022"
author: "Liza Dubinsky, Max Lauster, Sokona Mangane, Dieter Villegas"
output:   
  html_document:
    toc: true
    toc_float : true
    number_sections : true
    theme: united
    toc_depth: 4
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
  
## Executive Summary

This project was completed in collaboration with Jan Collins, the Assistant Director of the Maine Prisoner Advocacy Coalition and with guidance from Bates Professors Michael Rocque from the Sociology Department and M. Mena from the Anthropology Department. The focus of this project was to visualize prison and parole data to aid in the ongoing efforts of the Maine Prisoner Advocacy Coalition to campaign for the reinstatement of parole in Maine. This report includes animated visualizations and interactive maps to inform the work of the Maine Prisoner Advocacy Coalition.

Quick Issue Background

Methodology Overview

Recommendations/Next Steps

Summary/Conclusion

## List of Figures

## Introduction

### Background and Context

Issue Background/Statistics/Definitions

Work of MPAC

### Community Partner Identified Problem



What We Did

We hope that this report will complement the work of the Maine Prisoner Advocacy Coalition by visualizing existing criminal justice data to inform efforts to reinstate parole in Maine.

## Methodological Approach

### Depth and Accessibility of Data

### Our Approach
After realizing the discrepancies in the Vera data set, our team collected information from multiple sources. This information was tied together in two different data sets; a set that looks at prison statistics on a county level and a set on the state level. Our data knit together information from the Vera Institute, Urban Institute and the Bureau of Justice Statistics. This data was then utilized to understand the current state of the prison system in Maine and to build two interactive maps of the United States for further research. Through these visualizations of data our team aimed to aid in the understanding of how Maine will be impacted by the reimplementation of parole. 


## Results and Discussion

### Maine State Analysis
   
### New England Region Analysis

### Nationwide Tool for Further Data Exploration  
The data collected has been compiled into two separate interactive national maps that portray the information on a county and state level. The state map shows the number of adults on parole per one hundred thousand adult residents. This information is useful in showing which states have the most wide reaching parole and which states, like Maine, have not parole in recent years. It is worth noting that while Maine has had no parole recently, there are still a few individuals who were eligible for parole due to their sentences coming before parole was removed. The county level map displays the ratio of the jail population to the total population per one thousand residents. This normalizes the differences in population size and starts to look at which regions have higher and longer rates of incarcerations. Both of these maps will aid in further understanding the state of Maine prison reform compared to the rest of the US. 
## Recommendations for Next Steps
There is a lot of work still to be done with this research. Using the national maps alongside the Maine specific visualizations, it is important to identify which states have a similar make up of prison systems and how those states have dealt with parole. This is in service of understanding how reintroducing parole in Maine will impact the system and how many people may be eligible. This is a roundabout way of reaching these conclusions due to the lack of reliable information. This leads to the next recommendation which would be to lobby for more thorough data collection which focuses on parole eligibility, recidivism and costs related to parole. Without these more direct data points collected on an individual basis, any understanding of the impacts of the proposed Maine parole system will be loose approximations. Through more research and effective data collection/transparency, MPAC will be able to build a strong story of how parole will look in Maine. 
### Data Collection 

### Model Effect of Reinstatement of Parole in Maine

## References Cited

## Appendices
