---
title: "Max_File"
author: "Max Lauster"
date: "5/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Store string containing all required packages
my_packages <- c('bipartite', 'RColorBrewer')

```

Figure out which of these packages is already installed
``` {r}
# Store all installed packages
ya_installed <- library()$results[,1]

# Check whether required packages are already installed and grab only those that still need installation
need_install<-my_packages[!(my_packages %in% ya_installed)]

#install required packages
lapply({need_install}, install.packages, character.only = TRUE)

```

``` {r}
# Store all installed packages
ya_loaded <- (.packages())

# Check whether required packages are already installed and grab only those that still need installation
need_load<-my_packages[!(my_packages %in% ya_loaded)]

# Load required packages
lapply(need_load, require, character.only = TRUE)
```
```{r}
#install.packages("tidyverse")
#devtools::install_github("rstudio-education/dsbox")
#library(tidyverse)
#library(dsbox)
```

```{r}
parole_df <- read.csv("all_parole_years.csv")

```


```{r}
library(tidyverse)
library(dsbox)
by_state<-parole_df$state


```

```{r}
#install.packages("xaringanthemer")
library(tidyverse)
library(tidymodels)
#library(palmerpenguins)
library(knitr)
library(xaringanthemer)
#install.packages("maps")
#install.packages("corrplot")

library(maps)
library(ggplot2)
library(tidyverse)
library(corrplot)

library(dplyr)
#library(dsbox)
library(skimr)
library(robotstxt)
library(tidyr) 
library(leaflet) ## For leaflet interactive maps
library(sf) ## For spatial data
library(RColorBrewer) ## For colour palettes
library(htmltools) ## For html
library(leafsync) ## For placing plots side by side
library(kableExtra) ## Table output
#install.packages("geojsonio")
#install.packages("rgdal")
#install.packages("leaflet")
library(leaflet)
#install.packages("geojsonio")
library(geojsonio)
library(sf)
library(leaflet)
#install.packages("sf")
library(RColorBrewer)
```

```{r}
states <- geojsonio::geojson_read(x = "https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json"
        , what = "sp")
class(states)

library(readr)
states_all <- read.csv("all_parole_years.csv")
```


```{r echo = FALSE, warning = FALSE, message = FALSE}
#states_all <- states_all %>%
  #mutate(name = str_to_lower(str_replace_all(STATE, pattern = "_", replacement = " ")))

states <- st_as_sf(states)
states <- states %>%
  mutate(name = str_to_lower(name))

parole_df <- parole_df %>%
  mutate(state = str_to_lower(state))
  
state_parole <- parole_df %>%
  left_join(states, by = c("state"="name")) %>%
  st_as_sf()

#%%%%%%%% Merging Labels
state_parole$label <- ""
for(i in 1:nrow(state_parole))
  {
  state_parole$label[i]<- paste(state_parole$state[i], state_parole$number_on_parole_per_100000_us_adult_residents[i], sep = ": ")
  
  state_parole$label[i]<- paste(state_parole$label[i], "# on Parole/100,000 Adults", sep = " ")
  }
#%%%%%%%%

state_parole <- state_parole %>%
  filter(year==1996)
  #mutate(total_exp_per_student = TOTAL_EXPENDITURE/GRADES_ALL_G)
  
#this is for changing color 
bins <- c(0, 100, 200, 300, 400, 500, 600, 700, 800, 2000)
pal <- colorBin("Greens", domain = state_parole$number_on_parole_per_100000_us_adult_residents, bins = bins)

```


```{r echo = FALSE, warning = FALSE, message = FALSE}
labels <- sprintf("<strong>%s</strong><br/>%g Parole/100000 US Adults",
                  state_parole$state, state_parole$number_on_parole_per_100000_us_adult_residents) %>% lapply(htmltools::HTML)

```

```{r}

leaflet(data = state_parole) %>%
  addTiles()%>%
  setView(lng = -80,
          lat = 34.5,
          zoom = 4) %>%
  addPolygons(fillColor = ~pal(state_parole$number_on_parole_per_100000_us_adult_residents),
              fillOpacity = 1,
              color = "blue",
              opacity = 0.1,
              weight = 1,
              highlight = highlightOptions(
                weight = 3,
                color = "blue",
                fillOpacity = .2,
                bringToFront = TRUE),
              label = labels) %>%
  addLegend(
  position = "topright",
  pal = pal,
  values = ~number_on_parole_per_100000_us_adult_residents,
  title = "# of Adults on Parole/100000.",
  opacity = 1)
    

```
```{r}
#Importing state/County JSON containing fip and geometry of the counties
all_counties <- geojsonio:: geojson_read(x= "https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json", what= "sp")
#AK<-geojsonio::geojson_read(x = "https://raw.githubusercontent.com/billcccheng/us-county-boundary-api/master/states/AK.json", what = "sp")
by_year<-incar$year
maine_data <- by_year =="1970"
year_1970 <- incar[maine_data,]

```

```{r}

year_1970<- year_1970 %>%
  mutate(county_name = str_to_lower(str_replace_all(county_name, pattern = " County", replacement = "")))

all_counties <- st_as_sf(all_counties)
all_counties <- all_counties %>%
  mutate(NAME = str_to_lower(NAME))

joint_info_map <- year_1970 %>%
  left_join(all_counties, by = c("county_name" = "NAME")) %>%
  st_as_sf()


joint_info_map  <- joint_info_map  %>%
  #filter(total_pop) %>%
  mutate(total_pop = total_pop)
#this is for changing color 
bins <- c(0, 0.5,1,2,4,15)
pal <- colorBin("Blues", domain = joint_info_map$total_jail_pop/(joint_info_map$total_pop/1000), bins = bins)
```

```{r}
labels <- sprintf("<strong>%s</strong><br/>%g Total Jail Pop/Total Pop",
                 joint_info_map$county_name, joint_info_map$total_jail_pop/(joint_info_map$total_pop/1000)) %>% lapply(htmltools::HTML)
```

```{r}
joint_info_map%>%
leaflet() %>%
  addTiles()%>%
  setView(lng = -80,
          lat = 34.5,
          zoom = 4) %>%
  addPolygons(fillColor = ~pal(total_jail_pop/(total_pop/1000)),
              fillOpacity = 1,
              color = "black",
              opacity = 1,
              weight = 0.5,
              highlight = highlightOptions(
                weight = 3,
                color = "blue",
                fillOpacity = .2,
                bringToFront = TRUE),
              label = labels) %>%
  addLegend(
    position = "topright",
    pal = pal,
    values = ~total_jail_pop/(total_pop/1000),
    title = "Ratio of Jail Pop per 1000",
    opacity = 1)
```


