---
title: "Time_Served"
output: html_document
date: '2022-05-16'
---

###Time Served


```{r data cleaning}
library(readr)
library(readxl)
library(leaflet)
library(ggplot2)
library(dplyr)
library(tidyverse)



Time_Served_Trends <- read_excel("Time Served Trends.xlsx")


#states without parole
stateswop <- c("AZ", "CA", "DE", "FL", "IL", "IN", "KS", "ME", "MN", "NM", "NC", "OH", "OR", "VA", "WA", "WI")

#putting df into new object and changing the column names
Time_served_df <- Time_Served_Trends[2:582,]
colnames(Time_served_df)[3] <- "MEAN TIME SERVED (ALL OFFENSES)"
colnames(Time_served_df)[4] <- "MEAN TIME SERVED (VIOLENT OFFENSES)"
colnames(Time_served_df)[5] <- "MEAN TIME SERVED (NONVIOLENT OFFENSES)"
colnames(Time_served_df)[7] <- "MEAN TIME SERVED BY DECILE (BOTTOM 90%)"
colnames(Time_served_df)[8] <- "MEAN TIME SERVED BY DECILE (TOP 10%)"

Time_served_df <- Time_served_df %>%
  mutate(Parole = case_when(STATE %in% stateswop ~ "No",
                            TRUE ~ "Yes"
    ), across(c(3:8), as.numeric), across(c(3:8), round))

#creating shorter df for streamgraph
Time_served_df_plot <- Time_served_df %>%
  select(!4:8) %>%
  group_by(YEAR) %>%
  arrange(desc(YEAR))

devtools::install_github("hrbrmstr/hrbrthemes")
install.packages("viridis")
library(viridis)
library(hrbrthemes)
#library(gcookbook)
library(tidyverse)

colnames(Time_served_df_plot) <- c("State", "Year", "Avg_Time_Served_all", "Parole")

```

```{r creating plot}
#change labels
#color by parole or not parole in Country
#check for better way to visualize?



install.packages("ggrepel")
install.packages("ggtext")
install.packages("showtext")
library(tidyverse)
library(ggrepel)
library(ggtext)

library(showtext)
font_add_google("Lato")
showtext_auto()

Time_served_df_plot <- Time_served_df_plot[1:576,]
colnames(Time_Served_Trends) <- c("State", "Year","Avg_Time_Served_all","Avg_Time_Served_v","Avg_Time_Served_nv","time_served_90_percentile","Avg_Time_Served_Bottom_90_perc","Avg_Time_Served_Top_10_perc")


Time_Served_Trends[2:577,] %>%
  mutate(Parole = case_when(State %in% stateswop ~ "No",
                            TRUE ~ "Yes"),across(c(3:8), as.numeric)) %>%
  select(!4:8) %>%
  group_by(Year) %>%
  arrange(desc(Year)) %>%
  ggplot(aes(x=Year, y=Avg_Time_Served_all, group=State, color = Parole)) +
    geom_line(aes(group=State), size=0.5, alpha=0.5) +
    geom_line(aes(color=Parole), size=1.2 ) +
    scale_color_viridis(discrete = TRUE) +
    #theme_ipsum() +
    #theme(
     # legend.position="bottom",
      #plot.title = element_text(size=14),
      #panel.grid = element_blank()
    #) +
   labs(y= "The Average Time Served For All Offenses (Years)", title = "The Average Time Served For All Offenses In Each State") +
    facet_wrap(~State) + xlim(1993, 2014) + ylim(0, 8)

```

``` {r}

Time_served_All_States <- Time_Served_Trends[2:577,] %>%
  mutate(Parole = case_when(State %in% stateswop ~ "No",
                            TRUE ~ "Yes"),across(c(3:8), as.numeric)) %>%
  group_by(Year, Parole) %>%
  summarize(mean_all = mean((sum(Avg_Time_Served_all))/length(State)), mean_v = mean((sum(Avg_Time_Served_v))/length(State)), mean_nv = mean((sum(Avg_Time_Served_nv))/length(State)), mean_bottom_90 = mean((sum(Avg_Time_Served_Bottom_90_perc))/length(State)), mean_top_10 = mean((sum(Avg_Time_Served_Top_10_perc))/length(State)))
  
df1 <- Time_served_All_States[Time_served_All_States$Parole== "Yes",]   
df2 <- Time_served_All_States[Time_served_All_States$Parole== "No",]   


Sentence_Type.labs <- c("All Offenses", "Nonviolent Offenses","Violent Offenses")
names(Sentence_Type.labs) <- c("mean_all", "mean_nv", "mean_v")

Time_served_All_States %>%
  pivot_longer(cols = c("mean_all", "mean_v", "mean_nv"), names_to = "Sentence_Type", values_to = "Average_Sentence_Length") %>%
  ggplot(aes(x= Year, y = Average_Sentence_Length, color = Parole)) +
  geom_line() +
    geom_label_repel(aes(label=ifelse(Year == 2000 & Parole == "No","Wisconsin abolished parole",'')), size = 2, vjust = 0, nudge_y = 1.25, max.overlaps = 12) +
  geom_line(aes(x= Year, y = Average_Sentence_Length, color = Parole)) + 
  facet_wrap(~Sentence_Type, labeller = labeller(Sentence_Type = Sentence_Type.labs)) +
  labs(y= "The Average Time Served For Different Offenses (Years)", title = "The Average Time Served For Different Types of Offenses In All States") + xlim(1989, 2014) + ylim(0, 6.5)



```


```{r}

Time_served_All_States %>%
  pivot_longer(cols = c("mean_all", "mean_v", "mean_nv"), names_to = "Sentence_Type", values_to = "Average_Sentence_Length") %>%
  ggplot() + 
  geom_line(aes(x= Year, y = mean_top_10, color = Parole)) + 
  labs(y= "The Average Time Served (Years)", title = "The Average Time Served by the Top 10% of the Prison Pop. in All States") + xlim(1989, 2014) + ylim(0, 22.5)


Time_served_All_States %>%
  pivot_longer(cols = c("mean_all", "mean_v", "mean_nv"), names_to = "Sentence_Type", values_to = "Average_Sentence_Length") %>%
  ggplot() + 
  geom_line(aes(x= Year, y = mean_bottom_90, color = Parole)) +
  labs(y= "The Average Time Served (Years)", title = "The Average Time Served by the Bottom 90% of the Prison Pop. in All States") + xlim(1989, 2014) + ylim(0, 2.8)
  

```



